"""
Produktkategorier och ID Samlat i en dictionary
"""

produktkategorier = {
    "Business Awards, Hederspriser" : "127",
    "Bildgalleri" : "292",
    "Tombstones - corporate finance" : "228",
    "Dörrskyltar, företagsskyltar" : "263",
    "Glaspriser" : "130",
    "Gravera klockor" : "279",
    "Golfpriser" : "227",
    "Idrottsgrenar, kategorier" : "180",
    "Medaljband långa & korta" : "274",
    "Medaljer" : "243",
    "Medaljetuier" : "290",
    "Minnestavlor, Wall of Fame, KM, Sponsor" : "287",
    "Motivbrickor & Motivfolier" : "258",
    "Plaketter" : "122",
    "Pokaler" : "242",
    "Högtidsstunder och traditioner" : "163",
    "Klubbmärken" : "126",
    "Namnskyltar/Namnbrickor, nål eller magnet" : "132",
    "Lotter" : "214",
    "Ordförandeklubbor" : "226",
    "Prao-knappar" : "215",
    "Socklar" : "240",
    "Standar, vimplar, flaggor" : "154",
    "Tenn, silver, bägare, fat" : "125",
    "Specialtillverkade priser" : "278",
    "Swatkins Awards" : "223",
    "Uppmuntringspriser" : "277",
    "Jumbopris" : "255",
    "Fickpluntor" : "256",
    "Champagnesablar" : "254",
    "Vin-Whiskyglas" : "217",
    "Badmintonpriser" : "281",
    "Tennispriser" : "280",
    "Bordtennispriser" : "282",
    "Glas" : "269",
    "Prisrosetter häst & hund" : "123",
    "Gravyrskylt vandringspris" : "294",
    "Företagsskyltar" : "293",
    "Fasadsiffror & bokstäver" : "288",
    "Basketpriser" : "184",
    "Bodyfitnesspriser" : "276",
    "Bowlingpriser, Boulepriser" : "197",
    "Crickettpriser" : "185",
    "Dartpriser" : "202",
    "E-sport" : "286",
    "Fiskepriser" : "200",
    "Friidrott, Löpning" : "187",
    "Fotbollspriser" : "186",
    "Gymnastik, Cheerleadingpriser" : "224",
    "Handbollspriser" : "189",
    "Hockeypriser" : "192",
    "Hästsport" : "190",
    "Innebandypriser" : "191",
    "Jakt" : "221",
    "Kampsportspriser" : "196",
    "Motorsport" : "198",
    "Padelpriser" : "283",
    "Pokerpriser" : "220",
    "Racketsport" : "194",
    "Skyttepriser" : "203",
    "Vattensportpriser" : "204",
    "Vintersportpriser" : "206",
    "Volleybollpriser" : "195",
    "Övrigt" : "211",
    "Medaljer Neutrala" : "244",
    "Medaljer Präglade" : "245",
    "Medaljer Specialtillverkade" : "246",
    "Medaljband långa & korta" : "247",
    "Medaljaskar & etuier" : "248",
    "Rea-medaljer" : "289",
    "Pokaler Små & Mellan" : "250",
    "Pokaler Stora" : "251",
    "Pokaler Exklusiva" : "252",
    "Pokaler Mycket Exklusiva" : "253",
    "Broderade märken" : "155",
    "Pins, emaljerade märken" : "156",
    "Heraldiska sköldar" : "160",
    "Tillval till årsplåt" : "295",
}
